### ISSUE TITLE
Spawning jet, bodyguards, escort

### ISSUE THREAD

**Issue by heni015** [xesdoog/Billionaire-Script#1]
1. This script was spawning a jet, when one exists in hangar at Los Santos, one on one, max i saw 2 on one Jet.
Button to Dissmis not returning them. I must manually delete 2 to get flight cuz they stuck.

2. Bodyguard can follow player to a Jet, they only stayed in spawned place.

3.Escorts was so slow at traffic, they must override on signals maybe and be closer to a Limo :D

But script was nice :D

**Comment by xesdoog** [comment]
Thank you for your feedback.
1. Yes, the jet tab needs to disable the spawn button. The logic is currently flipped, it will let you know that you've already spawned one but will spawn another one nonetheless instead of stopping the execution. Also the flight system is messed up but overall this is a template that will be improved over time.

2. Bodyguards were tested recently to make sure they follow you inside the jet and take flights with you. This was in single player so it needs to be tested in online too to make sure it works smoothly.

3. Escorts were reworked and will be updated soon. They can drive much better now (they still struggle with traffic at times) but they can follow you anywhere even offroad. ~I tried to make them leave and reenter the car but ended up braking some other functionalities. For now, only the driver will stay in the car and the other two can exit and re-enter (you can ask the driver to leave too by pressing a button if they're all inside their vehicle).~

- This script needs a lot more work but I'll upload an update in a few minutes.

~*keeping this issue open*~

**EDIT:** 
- All escorts can now leave/re-enter their vehicle without issues.
- Bodyguards were tested and they do follow you anywhere you go and enter any vehicle you enter. I took them for a few flights both in online and in SP. You were probably referring to **escorts** not *bodyguards* because those are intentionally blocked from entering any vehicle you're in except theirs.
- The jet spawn issue has been fixed and the flight system has been reworked. You can now skip the landing process if your pilot takes too long to land.

*closing as completed.*
